-- EXC A

SELECT produto, valor
FROM VENDAS
WHERE valor > (
SELECT MIN(VALOR)
FROM VENDAS
WHERE CATEGORIA = 'Eletrônicos'

);

-- EXC B

SELECT VENDEDOR, PRODUTO, VALOR
FROM VENDAS
WHERE VALOR = (SELECT MAX(VALOR )FROM VENDAS);

-- EXC C

SELECT DISTINCT categoria
FROM VENDAS v
WHERE valor > (SELECT AVG(valor) FROM VENDAS);

-- EXC D

SELECT * FROM (
    SELECT vendedor, produto, valor,
    ROW_NUMBER() OVER (PARTITION BY vendedor ORDER BY valor DESC) AS RANKING
    FROM VENDAS
) t
WHERE RANKING <= 3 
ORDER BY vendedor, RANKING ASC;

